var textes = {
  fr: `
<h2>Conférence internationale en épigénétique des objets mécaniques</h2>
<h3>Montréal, le 15 octobre 2092</h3>
<h3>Texte d’ouverture par la conférencière Malaïka Kayitesi</h3>
<h3>« L’empreinte du gène mécanique (EGM), d’hier à aujourd’hui »</h3>

<p>Université de Zurich, 2019 : des chercheurs créent des codes, inscrits ensuite dans un brin d’ADN. Ils intègrent ce brin dans la matière inerte des objets mécaniques.</p>

<p>L’objectif de l’invention était de rendre ces objets identifiables et reproductibles par une imprimante 3D. Personne ne se doutait que, moins d’une vingtaine d’années plus tard, cela ouvrirait une brèche dans l’évolution des organismes vivants. Les milliers de nanocapsules, portant chacune le code des objets entiers dans une mémoire de 215 000 pétaoctets, ont fait leur place dans l’ADN des organismes vivants et ont généré l’impossible : elles ont donné vie à la matière inerte.</p>

<p>Si l’hypothèse d’un échange génétique horizontal entre les vivants - processus par lequel un organisme intègre du matériel génétique provenant d'un autre organisme sans en être le descendant - semait la controverse dans la communauté scientifique, le croisement entre les séquences comprises dans les nanocapsules des objets inertes et l’ADN des organismes vivants a rapidement fait consensus, et cela avant même l’apparition de l’évidence physique. C’est en 2037 qu’une chercheuse de l’université de Bangalore découvre par hasard une anomalie au sein de la séquence d’ADN d’un Malcoha à bec vert. Ce que nous appelons dorénavant « l’empreinte du gène mécanique » (EGM) a été causé, dans ce cas, par une collision avec un drone Mavic Air 25. Un an après cette découverte, l’empreinte du gène mécanique est détectée dans près de 45 % des organismes vivants soumis au test EGM à l’échelle de la planète.</p>

<p>La même année, on découvre une nouvelle espèce de plante envahissante présentant des caractéristiques physiques surprenantes : elle vient d’une rencontre entre l’algue Acetabularia acetabulum et le radar ALTAIR. La découverte est d’autant plus étonnante que ces plantes ont pour origine une transmission du vivant vers l’objet mécanique et non l’inverse. Le Centre de recherche sur la génétique des objets mécaniques de l’université de Thamar, dès les années 20, dévoile que plusieurs sociétés militaires privées (SMP) ont intégré, à l’intérieur des nanocapsules des objets mécaniques, des séquences d’ADN d’organismes vivants pour offrir à certains de leurs outils et certains de leurs véhicules de transport une meilleure performance. Ainsi, on observe que les codes des nanocapsules des chars d’assaut ont été mélangés avec ceux des gènes de scorpions, d’oiseaux de proie et de crustacés, permettant d’obtenir une souplesse dans l’articulation mécanique, une meilleure vitesse de déplacement et une discrétion sur le plan sonore. On s’aperçoit qu’une fois les gènes exprimés, la contamination de l’objet mécanique vers le vivant est amorcée et difficile à contenir.</p>

<p>Les chercheurs du Centre international de recherche sur l’épigénétique des objets mécaniques, deux ans après sa création en 2038, découvrent que l’intrusion de l’information d’une nanocapsule d’un objet inerte dans un organisme vivant se produit à la manière d’un virus. Une fois en contact avec l’hôte, les informations mécaniques se répliquent à l’aide du matériel génétique de l’organisme vivant et altère ses programmes de fonctions intracellulaires au profit du gène mécanique. L’organisme vivant devient à son tour un agent « contaminant ». Il peut modifier toute une population d’organismes vivants de différentes espèces en plus de transmettre les gènes de manière verticale, c’est-à-dire par héritage génétique - les capacités de reproduction de l’organisme hybride n’étant pas compromises.</p>

<p>Grâce à des recherches conjointes menées par les départements d’épigénétique des universités de Sao Paulo, de Weizmann et d’Osaka, nous savons depuis 2040 que 25 % des organismes vivants renfermant l’empreinte du gène mécanique portent ce gène à l’état latent. Si l’identification rapide de tous les organismes affectés, afin d’en assurer la destruction, la vitesse de transmission du gène mécanique demandait d’autres pistes de solution. C’est l’Équipe de recherche sur les conditions d’expression du gène mécanique de l’Université de Koudougou qui propose, lors du Sommet sur l’empreinte du gène mécanique de 2062 à Buenos Aires, une avenue prometteuse. Ses recherches, avec des données probantes à l’appui, confirment que le gène mécanique s’éveille et s’exprime seulement lorsque l’organisme détecte une menace réelle pour sa survie. Cela est dû au fait que les objets mécaniques sont mieux adaptés aux changements climatiques que les organismes vivants. De nouvelles stratégies radicales de conservation des milieux naturels permettraient donc de minimiser l’expression du gène mécanique dans les organismes vivants.</p>

<p>Lors de la désormais célèbre conférence internationale « Le gène mécanique : transmission et expression », de Budapest en 2064, on présentait une nouvelle hypothèse sur les modalités de la transmission du gène. Elle nous avait d’abord semblé aléatoire : la similarité physique entre les organismes vivants et les objets serait ce qui constitue la véritable porte d’entrée du gène mécanique. L’empreinte génomique des objets sur les organismes vivants dépend ainsi de la forme interne et de l’apparence des objets comme des organismes. Le biomimétisme, au cœur de la Stratégie internationale de la transition écologique de l’ONU, en 2032, aurait donc emboîté le pas devant le désastre auquel nous faisons face aujourd’hui. Cet aspect des plus inusités du domaine de la génétique représente une piste importante à investiguer, car comprenant mieux ce mécanisme de mimétisme, peut-être pourrions-nous mieux le détourner et l’utiliser à bon escient.</p>

<p>Lors de la première découverte de l’occurrence de l’empreinte du gène mécanique dans l’organisme vivant, la préoccupation principale a été de comprendre son effet sur l’ADN humain. Les études les plus récentes menées sur la présence du gène mécanique chez l’être humain indiquent que 7 % de l’ADN prélevé contient une faible empreinte du gène mécanique. Il n’est pas encore prouvé que son expression peut avoir lieu dans un corps humain et que celui-ci peut le transmettre. L’entreprise préventive de destruction de tout objet anthropomorphique a permis de prévenir l’expression du gène, mais la menace est bien réelle : le système d’encodage artificiel d’information injecté dans les objets est entré dans le corps humain et reste donc susceptible de se réveiller si les conditions environnantes deviennent favorables.</p>

<p>Le brevetage du vivant, déjà un enjeu éthique depuis un centenaire, déclenche aujourd’hui une guerre entre les inventeurs des codes génétiques des objets qui revendiquent un brevet sur les organismes hybrides. Les inventeurs des nanocapsules s’en sont d’abord tenus à la poursuite, pour 25 millions de dollars, des agences militaires privées pour l’appropriation et le détournement des nanocapsules d’un drone Lockheed Martin RQ-170 Sentinel. En y injectant les gènes d’une raie manta océanique aussi appelée « diable de mer », ils ont modifié le code original. Les agences militaires privées argumentent sur le fait que l’injection aurait non seulement permis d’améliorer l’aérodynamisme de l’objet mécanique, dont elles sont les créatrices, mais qu’elle aurait aussi donné la possibilité de le faire voyager sous l’eau et de lui offrir un hydrodynamisme hors pair. Les nanocapsules ne font que répliquer un objet dont les inventeurs de codes ne sont pas les créateurs, ce à quoi les inventeurs des codes génétiques des objets répondent qu’une telle hybridation n’aurait pu avoir lieu sans leur invention.</p>

<p>Les inventeurs des nanocapsules revendiquent aussi un droit de propriété sur les organismes hybridés de manière générale soulevant des enjeux éthiques et politiques fondamentaux.  Les défenseurs des droits pour les organismes vivants mécaniques argumentent que, lorsque le processus par lequel ces organismes hybrides sont générés et par lequel ils survivent dans le monde est autonome, nous devons considérer l’hybridation comme un phénomène évolutif et adaptatif important. Ce sont des organismes vivants à part entière et nous avons le devoir de les protéger. L’association pour la conservation de la nature indigène présente quant à elle une opinion différente : il faut éradiquer les végétaux comportant des gènes mécaniques et multiplier nos végétaux indigènes (qui ne comportent ni OGM ni EGM) dans des endroits protégés afin de se refaire une nature qui protégera les autres organismes vivants, notamment ceux du règne animal duquel fait partie l’être humain.</p>

<p>Les néonaturalistes, pour leur part, se réjouissent du retour de la possibilité pour tous de faire la découverte de nouvelles espèces, de les documenter et ainsi de participer à l’élaboration d’une nouvelle taxonomie. Ils revendiquent ce nouveau « naturel » qu’il faut apprendre à accueillir plutôt qu’à l'éradiquer. L’enjeu s’est radicalisé avec la compréhension du fait que les gènes de différents règnes ont été mixés et que les espèces ne peuvent plus être classifiées de la même manière. Les mixages opérés par les militaires ont causé une unicité du vivant, de ses différents règnes. On pense au Blackbird SR-71 dans lesquels ont été introduits les gènes d’un faucon et d’un caméléon, mais aussi de tulipes. Cela a engendré un croisement horizontal, non seulement entre le gène mécanique et le vivant, mais entre le règne végétal et le règne animal.</p>

<p>Le codage artificiel ayant été conçu pour perdurer durant des millénaires et pour se reproduire, cela fait du gène mécanique un gène fort pour l’évolution des espèces. Sous forme de billes de dioxyde de silicium, les brins d’ADN ainsi encapsulés supportent les traitements chimiques et thermiques. Devrions-nous encourager l’hybridation, la théoriser comme une évolution nécessaire du vivant? Les recherches les plus récentes convergent toutes vers la nécessité du gène mécanique pour soutenir le vivant durant cette période de transition où nous nous trouvons. Également parce que l’EGM permet la préservation de milliards d’espèces en voie de disparition puisque, de toute manière, un retour vers l’ADN original demeure possible. En effet, les plus récentes découvertes, menées au Centre de recherche sur la dégradation de l’EGM de Gaspé (Québec), indiquent que des organismes comprenant un haut taux d’empreintes du gène mécanique peuvent revenir à un état pré-EGM lorsque placés au sein d’un milieu naturel préservé. C’est le cas de la mouche à chevreuil du Québec qui, une fois transportée dans la Réserve faunique de Matane, délaisse petit à petit le gène mécanique jusqu’à évacuer toutes traces de son empreinte.</p>
`,
  en: `asdf`
}
